(ns tiltontec.demo.todoMVC.common
  (:require
    ["package:flutter/material.dart" :as m]
    ["package:shared_preferences/shared_preferences.dart" :as prefs]
    [tiltontec.flutter-mx.core :as fx]
    [tiltontec.cell.base :refer [cinfo minfo] :as cty]
    [tiltontec.util.base :refer [dprn dp dpx]]))

(defn title-red []
  (.fromRGBO m/Color 184 63 69 0.5))

(defmacro my-todo-list []
  `(tiltontec.model.core/mget (tiltontec.model.core/fasc :app) :todo-list))
