(ns tiltontec.matrix.foundation
  (:require [clojure.string :as str]))

(defprotocol PObserver
  (observe [this prop me new-value prior-value cell]))

(deftype MXImplementer [])

(deftype CBFactory [value]
  ;; tells fx-render to call the value as a function with an optional parent.
  ;; this allows us to defer evaluation without heavy macrology.
  :extends MXImplementer)

;; --- mx-common ----------------------

(defn mx-type [it]
  (when-let [m (meta it)]
    (:mx-type m)))



