(ns tiltontec.mx-flutter.shared-pref
  (:require
    ["package:shared_preferences/shared_preferences.dart" :as prefs]
    ;; todo merge cells NSes
    [tiltontec.util.base :refer [dprn dp dpx]]
    [tiltontec.cell.base :refer [cinfo minfo] :as cty]
    [clojure.walk :as walk]
    [cljd.string :as str]))

(def +db+ (atom nil))

(defn ^:async  ^#/(Future prefs/SharedPreferences) get-db []
  (or @+db+
    (let [db (await (.getInstance prefs/SharedPreferences))]
      (reset! +db+ db))))