(ns tiltontec.testing
  (:require
    [tiltontec.util.base :refer [dp]]
    [tiltontec.test.cell-core :refer [run-tests] :as test-cell-core]
    [tiltontec.test.hello-cells :refer [run-tests] :as hello-cells]
    [tiltontec.test.evaluate :refer [run-tests] :as test-eval]
    [tiltontec.test.observer :refer [run-tests] :as test-obs]
    [tiltontec.test.integrity :refer [run-tests] :as test-integ]
    [tiltontec.test.lazy-cells :refer [run-tests] :as test-lazy]
    ;[tiltontec.test.synapse :refer [run-tests] :as test-syn]
    [tiltontec.test.model-core :refer [run-tests] :as md]
    [tiltontec.test.family-kids :refer [run-tests] :as fm-kids]
    ))

(defn run-test-lazy []
  (test-lazy/run-tests)
  (dp :test-lzy-ok))

(defn run-tests []
  (dp :start-tests)
  (do (test-cell-core/run-tests)
      (dp :cell-core-ok))
  ;(hello-cells/run-tests)
  ;(dp :hello-cells-ok)
  ;(test-eval/run-tests)
  ;(dp :eval-ok)
  ;(test-obs/run-tests)
  ;(dp :obs-watch-ok)
  ;(test-integ/run-tests)
  ;(dp :integ-ok)
  ;(test-lazy/run-tests)
  ;(dp :lazy-ok)
  ;(md/run-tests)
  ;(dp :md-ok)
  ;(fm-kids/run-tests)
  ;(dp :fm-kids-ok)
  ; TODO synapses (test-syn/run-tests)
  ;(hello-cells/run-tests)
  (dp "testing-OK"))

