(ns tiltontec.test.observer
  (:require
    [tiltontec.util.base
     :refer [trx dp prog1]]
    [tiltontec.cell.base
     :refer [without-c-dependency c-optimized-away? c-formula? c-value c-optimize
             c-unbound? c-input?
             mx-type cells-init c-callers c-useds
             c-model mdead? c-valid? c-useds c-ref? md-ref?
             c-state +pulse+ c-pulse-observed
             *call-stack* *defer-changes*
             c-rule c-me c-value-state c-callers
             unlink-from-callers *causation*
             c-prop-name c-synaptic?
             c-pulse c-pulse-last-changed c-ephemeral? c-prop
             *depender* *not-to-be*
             *c-prop-depth* md-prop-owning? c-lazy] :as cty]
    [tiltontec.cell.evaluate :refer [c-get]]
    [tiltontec.cell.observer :refer [fn-obs]]

    [tiltontec.cell.core
     :refer [cF cF+ cI creset!]]
    ))

(defn t-formula []
  (cells-init)
  (let [bingo (atom false)
        c (cF+ [:prop :bingo
                :watch (fn-obs
                         (reset! bingo true))]
            (+ 40 2))]
    (assert (dart/is? (mx-type c) cty/CellFormula))
    (assert (= (c-value-state c) :unbound))
    (assert (= #{} (c-callers c)))
    (assert (= #{} (c-useds c)))
    (assert (not (c-input? c)))
    (assert (not (c-valid? c)))
    (assert (nil? (c-model c)))
    (assert (= (c-get c) 42))
    (assert (= 42 @c))                                      ;; ie, optimized-away
    (assert @bingo)
    ))

(defn test-input []
  (let [bingo2 (atom 0)
        c (cI 42 :prop :bingo2
            :watch (fn-obs
                     (dp :test-input-obs-runs!!!)
                     (swap! bingo2 inc)))]
    (assert (dart/is? (mx-type c) cty/Cell))
    (assert (= (c-value-state c) :valid))
    (assert (= #{} (c-callers c)))
    (assert (c-input? c))
    (assert (c-valid? c))
    (assert (nil? (c-model c)))
    (assert (= :bingo2 (c-prop c) (c-prop-name c)))
    (assert (= (c-get c) 42))
    (assert (= 1 @bingo2))

    (creset! c 54)
    (assert (= (c-get c) 54))
    (assert (= 2 @bingo2))))

(defn t-custom-obs []
  (let [bobs (atom nil)
        b (cI 2 :prop :bb
            :watch (fn-obs
                     (dp :watch-b prop me new old)
                     (reset! bobs new)))
        cobs (atom nil)
        c (cF+ [:watch (fn-obs [prop me new old c]
                         (trx prop me new old)
                         (reset! cobs new))]
            (* 10 (c-get b)))]
    (do
      (dp :MX-built!------------------)
      (assert (= @bobs nil) (str "@bobs not nil: " @bobs))
      (assert (= (c-get b) 2))
      (assert (= @bobs 2) (str "@bobs not nil: " @bobs))
      (assert (= (c-get c) 20))
      (assert (= @cobs 20))
      (creset! b 3)
      (assert (= 3 @bobs))
      (assert (= 30 (c-get c)))
      (assert (= 30 @cobs)))))

(defn run-tests []
  (t-formula)
  (test-input)
  (t-custom-obs)
  (dp :observer-tests-OK))


