(ns tiltontec.test.shared-preferences-test
  (:require
    ["dart:developer" :as dev]
    ["dart:math" :as mth]
    ["dart:convert" :as convert]
    ["package:flutter/widgets.dart" :as w]
    ["package:path/path.dart" :as path]
    ["package:shared_preferences/shared_preferences.dart" :as prefs]
    [tiltontec.util.base :refer [dprn dp dpx]]
    [tiltontec.cell.base :refer [cinfo minfo] :as cty]
    [tiltontec.model.core :refer [mget mset! mset!x mswap! fasc mkids mpar] :as md]
    [tiltontec.mx-flutter.core :as fx]


    [tiltontec.mx-flutter.store :as store]
    [tiltontec.demo.todoMVC.todo :refer [my-app] :as todo]
    [clojure.walk :as walk]
    ))


(defn test []
  (dp :prefs-test!!!!!! )
  (dp :json? (convert/jsonEncode {"a" 42}))
  (dp :json? (convert/jsonEncode (walk/stringify-keys {:a 42})))
  ;(dp :json? (convert/jsonEncode {:sid 42 :title "walk dog" :completed false}))
  (.ensureInitialized w/WidgetsFlutterBinding)

  (let [prefs (await (.getInstance prefs/SharedPreferences))]
    (dp :got-dbi! prefs)
    ;; await prefs.setInt('counter', counter);
    (.setInt prefs "counter" 42)
    (.setString prefs "todo/00042" (convert/jsonEncode
                                     (walk/stringify-keys
                                       {:sid 42 :title "walk dog" :completed false})))
    (let [td (.getString prefs "todo/00042")]
      (dp :reread-raw  td )
      (dp :reread  (convert/jsonDecode td))))
  )