(ns tiltontec.test.shared-preferences-test
  (:require
    ["dart:developer" :as dev]
    ["dart:math" :as mth]
    ["dart:convert" :as convert]
    ["package:flutter/widgets.dart" :as w]
    ["package:path/path.dart" :as path]
    ["package:shared_preferences/shared_preferences.dart" :as prefs]
    [tiltontec.util.base :refer [dprn dp dpx]]
    [tiltontec.cell.base :refer [cinfo minfo] :as cty]
    [tiltontec.model.core :refer [mget mset! mset!x mswap! fasc mkids mpar] :as md]
    [tiltontec.mx-flutter.core :as fx]


    [tiltontec.mx-flutter.store :as store]
    [tiltontec.demo.todoMVC.todo :refer [my-app] :as todo]
    [clojure.walk :as walk]))


(defn test []
  (dp :prefs-test!!!!!! ))